version: "3.4"


services:

  web:
    image: studreply
    networks:
      - net
    environment:
      DB_HOST: "postgres"
      MINIO_HOST: "minio"
      TELEGRAM_TOKEN: $TELEGRAM_TOKEN
    command: runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - setup
      - minio
    restart: unless-stopped

  bot:
    image: studreply
    networks:
      - net
    environment:
      DB_HOST: "postgres"
      MINIO_HOST: "minio"
      TELEGRAM_TOKEN: $TELEGRAM_TOKEN
    command: bot
    depends_on:
      - setup
      - minio
    restart: unless-stopped

  setup:
    image: studreply
    networks:
      - net
    environment:
      DB_HOST: "postgres"
      MINIO_HOST: "minio"
      TELEGRAM_TOKEN: $TELEGRAM_TOKEN
    command: setup
    restart: on-failure
    depends_on:
      - migrations

  migrations:
    image: studreply
    networks:
      - net
    environment:
      DB_HOST: "postgres"
      MINIO_HOST: "minio"
      TELEGRAM_TOKEN: $TELEGRAM_TOKEN
    command: migrate
    restart: on-failure
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    networks:
      - net
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "studreply"
    restart: unless-stopped
    ports:
      - "5432:5432"

  minio:
    image: bitnami/minio:2022.10.8
    networks:
      - net
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: "password"
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    

networks:
  net:
