# Generated by Django 4.1.7 on 2023-04-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='previous_state',
            field=models.TextField(default='new'),
        ),
    ]
