# Generated by Django 3.2.19 on 2023-05-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_student_previous_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='faculty',
            field=models.TextField(default=''),
        ),
    ]
