# Generated by Django 3.2.19 on 2023-05-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_request_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='destination',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
