# Generated by Django 3.2.19 on 2023-05-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_request_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='entered_faculty',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='request',
            name='destination',
            field=models.TextField(db_index=True),
        ),
    ]
