# Generated by Django 3.2.19 on 2023-05-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20230521_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='entered_faculty',
            field=models.TextField(null=True),
        ),
    ]
