# Generated by Django 3.2.19 on 2023-05-21 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_request_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='entered_faculty',
        ),
    ]
